### ISSUE TITLE
Aaltoverb 2: Does not show up in Live's Plug-ins Folder for AU (works for VST3)

### ISSUE THREAD

**Issue by wellsoliver** [madronalabs/plugin-issues#28]
Altoverb 2.0.1 on an Intel Mac in MacOS Monterrey (12.3.1) on Live 11.1.1: after installing from the 64-bit VST3/AU link, it does not show under the Madrona Labs folder under Plug-ins for AU, but it does for VST3. Not a big deal, I just usually have VSTs disabled so I didn't see it, and I think it should show for the AU list. Here are two little screenshots that show the difference...

<img width="233" alt="Screen Shot 2022-05-08 at 12 01 02 PM" src="https://user-images.githubusercontent.com/142900/167311505-53fc3984-65e7-48b7-849f-1d671543172a.png">

<img width="213" alt="Screen Shot 2022-05-08 at 12 01 05 PM" src="https://user-images.githubusercontent.com/142900/167311509-2992a793-ea25-45c8-93ae-18068bb3a2a9.png">

**Comment by madronalabs** [comment]
Hi Wells, This is pretty common with AU plugins, I think you probably just need to clear your Audio Units cache. Try this:

If the plugin passes validation but still does not show in the Insert menus, try the following steps:

- Close the DAW
- in Finder, hold down the Option key, click on the Go menu at the top of your screen and select Library
- Delete the following files from ~/Library, if they are present:

```
~/Library/Caches/com.apple.audiounits.cache
~/Library/Caches/AudioUnitCache/
~/Library/Preferences/com.apple.audio.InfoHelper.plist
~/Library/Preferences/com.apple.audio.SandboxHelper.plist
```

- Restart your computer

**Comment by wellsoliver** [comment]
Had no idea AUs were cached like that, thanks. All good now.

**Comment by madronalabs** [comment]
Glad to hear.
