### ISSUE TITLE
SUMU filter type incorrectly recalled in presets

### ISSUE THREAD

**Issue by p1afff** [madronalabs/plugin-issues#38]
[RES module] 
Filter type is not correctly recalled in some (or all ?) presets. 
Load a preset, like Playback Default preset (I also tried in several others)
Filter type is displayed as lopass
if you move the freq control, nothing happens.
If you change filter type then get back to lopass, NOW freq knob works OK. 

In these cases, it seems that filter is more likely in THRU mode 
When preset has Res modulation input set, issue does not happen

M1 Max Monterey, Live 11.3.11 / VST3

**Comment by madronalabs** [comment]
fixed
